import './components/header';
import './components/swiper';
import './components/fancy';
import './components/catalog';
import './components/common';
import './components/dropzone';
import './components/calculator';
import './components/masonry';
import './components/cart'
import './components/validate'
