import './components/header';
import './components/swiper';
import './components/fancy';
// import './components/calc';
import './components/catalog';
import './components/common';
import './components/sort';
//import './components/cart';
import './components/dropzone';
//import './components/calcNew';
import './components/calculator';
import './components/masonry';
