<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Privacy' => 'Политика конфиденциальности',
    'Delivery and Payment' => 'Доставка и оплата',
    'Cart' => "Корзина",
    'HomeLink' => 'Главная',
    'Catalog' => "Каталог",
    'Footer Phone' => 'Телефон',
    'Footer Email' => 'Почта',
    'Footer Address' => 'Адрес',
    'Footer Contacts Block' => 'Контакты',
    'We are in IG' => "Наша страничка в Instagram",
    "We are in WA" => 'Наш контакт в WhatsApp',
    "We are in Telegram" => "Мы в Telegram",
    "We are in VK" => "Наша страница во Вконтакте",
    "We are in Avito" => "Мы на Avito",
    "We are in LiveMaster" => 'Наша страница LiveMaster',
    "Send WhatsApp Message" => "Написать в WatsApp",
    "Send Telegram Message" => "Написать в Telegram",
];
