<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Privacy' => 'Политика конфиденциальности',
    'Delivery and Payment' => 'Доставка и оплата',
    'Cart' => "Корзина",
    'HomeLink' => 'Главная',
    'Catalog' => "Каталог",
    'Footer Phone' => 'Телефон',
    'Footer Email' => 'Почта',
    'Footer Address' => 'Адрес',
    'Footer Contacts Block' => 'Контакты',
    'We are in IG' => "Наша страничка в Instagram",
    "We are in WA" => 'Наш контакт в WhatsApp',
    "We are in Telegram" => "Мы в Telegram",
    "We are in VK" => "Наша страница во Вконтакте",
    "We are in Avito" => "Мы на Avito",
    "We are in LiveMaster" => 'Наша страница LiveMaster',
    "Send WhatsApp Message" => "Написать в WatsApp",
    "Send Telegram Message" => "Написать в Telegram",
    'Total amount except delivery' => 'Сумма без учета доставки',
    "Total amount" => "Итого:",
    "In Cart" => "В корзине",
    "Checkout" => "Оформить заказ",
    'With privacy policy' => "Политикой конфиденциальности",
    "You are agree if submit" => "Нажимая на кнопку «Оформить заказ», вы соглашаетесь с",
    "Payment rules" => "Вы отдаете деньги курьеру, курьер отдает вам чек, подтверждающий оплату.",
    "Delivery Button Text" => "Доставка",
    "Pickup Button Text" => "Самовывоз",
    "Submit order" => "Оформить заказ",
    'Answers and questions' => "Вопросы и ответы",
    "Menu Item Rodent" => "Шиншиллы",
    "Menu Item Dog" => "Собаки",
    "Menu Item Cat" => "Кошки",
    "Menu Item Bird" => "Птицы",
    "Menu Item Personal Order" => "Персональный заказ",
    "Menu Item Catalog" => "Каталог",
    'Delivery' => "Доставка",
    'Page Title Chinchilles' => 'Витрины для шиншилл, дегу',
    "Breadcrumbs Chinchilles" => "Шиншиллы",
    'Height {height} Width {width} Depth {depth} mm' => 'В{height} Ш{width} Г{depth} мм',
    'In available' => 'В наличии',
    "Sidebar Configuration" => "Конфигурация",
    'Sidebar Characteristics' => "Характеристики",
    'Base color' => 'Цвет каркаса',
    'Base material' => "Боковые стенки",
    'Base Size' => "Размер",
    "Price with content" => "Цена с учетом наполнения",
    'To cart' => "В корзину",
    'Constructor Size' => "Размер",
    'Size Height' => "В",
    'Size Width' => "Ш",
    'Size Depth' => "Г",
    'Size mm' => " мм",
];
